# Generated by Django 5.1 on 2024-08-28 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DailyExpense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('purpose', models.CharField(max_length=20)),
                ('income', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('expense', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('daily_expense_date', models.DateTimeField()),
                ('descriptions', models.TextField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_expenses', to='dailyexpense.category')),
            ],
        ),
    ]
