# Generated by Django 5.1 on 2024-09-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyexpense', '0004_alter_dailyexpense_daily_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyexpense',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
