# Generated by Django 5.1 on 2024-09-29 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyexpense', '0005_dailyexpense_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyexpense',
            name='status',
        ),
    ]
